# -*- coding: utf-8 -*-
"""OR-Day-12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aPJci3PQkUDQFw6JCArI5s7BnMkwylm
"""

!pip install dwave-ocean-sdk -q

import numpy as np
from google.colab import userdata
from dwave.system import LeapHybridNLSampler
from dwave.optimization.generators import traveling_salesperson

N = 443
DISTANCE_MATRIX = np.fromfile(file='distances.csv', sep=',').reshape(N,N).tolist()

model = traveling_salesperson(distance_matrix=DISTANCE_MATRIX)
sampler = LeapHybridNLSampler(token=userdata.get('dwave_token'))
results = sampler.sample(model)

print(f"Runtime: {results.result().timing['run_time']/1000}ms")
print(f"Objective: {model.objective.state(0)}")